package isabelle.jedit

import isabelle.{GUI_Thread, Markup, Rendering, Text, XML, Value, Headless, Document, Sessions}
import javax.swing.JOptionPane
import java.io.{File => JFile}
import org.gjt.sp.jedit.View
import org.gjt.sp.jedit.textarea.JEditTextArea
import org.gjt.sp.jedit.buffer.JEditBuffer
import org.gjt.sp.jedit.jEdit

import scala.concurrent.{Promise, Await}
import scala.concurrent.duration.Duration

object Refactor {

  case class RenameResult(
      targetId: Option[Long],
      occurrences: List[(Document.Node.Name, List[Text.Range])]
  )

  // Known suffixes generated by Isabelle for derived constants
  // ## These are not currently being used ##
  private val derived_suffixes: List[String] =
    List("_def", "_simps", "_cases")

  /* Entry point */

  def rename(view: View): Unit = {
    GUI_Thread.now {
      val text_area = view.getTextArea()

      val entities =
        (for {
          doc_view <- Document_View.get(text_area)
          snapshot = Document_View.rendering(doc_view).snapshot
        } yield entity_at_caret(text_area, snapshot)).getOrElse(Nil)

      val target_name = entities.collectFirst { case ("constant", name, _) => name }
      val old_short_name = target_name.map(short_name)
      val current_file = view.getBuffer.getPath

      val (dialog, label) = progress_dialog(view)

      jEdit.getBuffers.foreach { buf =>
        if (buf.isDirty) buf.save(view, null)
      }

      val result_promise = Promise[RenameResult]()
      val progress = theory_progress(label)

      dialog.addWindowListener(new java.awt.event.WindowAdapter {
        override def windowClosing(e: java.awt.event.WindowEvent): Unit = {
          progress.stop()
          Headless_Handler.cancel()
          label.setText("Cancelling…")
        }
      })

      val thread_name = s"isabelle-rename-${target_name.getOrElse("unknown")}"
      new Thread(
        () => {
          try {
            val result = find_all_occurrences(target_name, current_file, progress)
            result_promise.success(result)
            ()
          } catch {
            case e: Throwable =>
              result_promise.failure(e)
              ()
          } finally {
            GUI_Thread.later { dialog.dispose() }
          }
        },
        thread_name
      ).start()

      dialog.setVisible(true) // blocks until dialog is gone

      if (!progress.stopped) {
        val rename_result = Await.result(result_promise.future, Duration.Inf)
        prompt_and_apply(view, rename_result, old_short_name)
      }
    }
  }

  /* All occurrences across all theories in ROOT */

  private def find_all_occurrences(
      target_name: Option[String],
      current_file: String,
      progress: isabelle.Progress
  ): RenameResult = {

    Headless_Handler.ensure_running(current_file, progress)
    val defining_theory = target_name.map(n => n.take(n.lastIndexOf('.')))
    val defining_node = Headless_Handler.nodes.find { name =>
      val short = name.theory.drop(name.theory.lastIndexOf('.') + 1)
      defining_theory.contains(short)
    }

    val (headless_id, all_ids) = defining_node match {
      case None => (None, Set.empty[Long])
      case Some(name) =>
        val snapshot = Headless_Handler.snapshot(name).get
        val id = entity_by_name("constant", target_name, snapshot)
        val ids = collect_all_entity_ids(target_name, snapshot)
        (id, ids ++ id.toSet)
    }

    val occurrences = for {
      id <- headless_id.toList
      name <- Headless_Handler.nodes
      snapshot <- Headless_Handler.snapshot(name).toList
      ranges = find_occurrences(id, all_ids, target_name, snapshot)
      if ranges.nonEmpty
    } yield (name, ranges)
    RenameResult(headless_id, occurrences)

  }

  /* UI: prompt user for new name and apply */

  private def prompt_and_apply(
      view: View,
      result: RenameResult,
      old_short_name: Option[String]
  ): Unit = {
    val ranges_str =
      if (result.occurrences.isEmpty) "  (none)"
      else
        result.occurrences
          .map { case (node_name, ranges) =>
            val header = s"  ${node_name.theory}:"
            val lines = ranges.map(r => s"    [${r.start}, ${r.stop})").mkString("\n")
            s"$header\n$lines"
          }
          .mkString("\n")

    val new_name: Option[String] = Option(
      JOptionPane.showInputDialog(
        view,
        s"ID: ${result.targetId.getOrElse("none")}\nMatches:\n$ranges_str\n\nEnter replacement name:"
      )
    )

    (new_name, old_short_name) match {
      case (Some(name), Some(old_name)) if name.nonEmpty =>
        apply_renames(result.occurrences, old_name, name)
        reload_buffers(view, result.occurrences.map(_._1))
      case _ => // User cancelled or left blank
    }
  }

  /* File rewriting */

  private def apply_renames(
      occurrences: List[(Document.Node.Name, List[Text.Range])],
      old_name: String,
      new_name: String
  ): Unit =
    occurrences.foreach { case (node_name, ranges) =>
      val path = isabelle.Path.explode(node_name.node)
      val text = isabelle.File.read(path)
      val result = ranges.sortBy(_.start).reverse.foldLeft(text) { (t, r) =>
        t.substring(0, r.start) + t.substring(r.start, r.stop).replace(old_name, new_name) +
          t.substring(r.stop)
      }
      isabelle.File.write(path, result)
    }

  private def reload_buffers(view: View, nodes: List[Document.Node.Name]): Unit =
    nodes.foreach { node_name =>
      val buf = jEdit.getBuffer(node_name.node)
      if (buf != null) buf.reload(view)
    }

  /* Entity lookup */

  def entity_at_caret(
      text_area: JEditTextArea,
      snapshot: Document.Snapshot
  ): List[(String, String, Option[Long])] = {
    val caret_range = JEdit_Lib.caret_range(text_area)
    snapshot
      .cumulate[List[(String, String, Option[Long])]](
        caret_range,
        Nil,
        Rendering.entity_elements,
        _ => { case (acc, Text.Info(_, XML.Elem(markup, _))) =>
          (Markup.Entity.unapply(markup), Markup.Entity.Occ.unapply(markup)) match {
            case (Some((kind, name)), occ_id) => Some((kind, name, occ_id) :: acc)
            case _                            => None
          }
        }
      )
      .flatMap(_.info)
  }

  def entity_by_name(
      kind: String,
      target_name: Option[String],
      snapshot: Document.Snapshot
  ): Option[Long] = target_name.flatMap { name =>
    snapshot
      .cumulate[Option[Long]](
        Text.Range(0, snapshot.node.source.length),
        None,
        Rendering.entity_elements,
        _ => {
          case (None, Text.Info(_, XML.Elem(markup, _))) =>
            (Markup.Entity.unapply(markup), Markup.Entity.Occ.unapply(markup)) match {
              case (Some((`kind`, `name`)), Some(id)) => Some(Some(id))
              case _                                  => None
            }
          case _ => None
        }
      )
      .flatMap(_.info)
      .headOption
  }

  /* Entity occurrence finding */

  def find_occurrences(
      target_id: Long,
      all_ids: Set[Long],
      target_name: Option[String],
      snapshot: Document.Snapshot
  ): List[Text.Range] = {
    val full_range = Text.Range(0, snapshot.node.source.length)

    val name_matches: String => Boolean = name =>
      target_name.exists(t => t == name || t.endsWith("." + name))

    // Matches derived names (e.g. myConst_def, myConst_simps)
    // Not an ideal solution, but derived names doesn't match
    // user-defined suffixes
    val matches_derived: String => Boolean = name =>
      target_name.exists { t =>
        val s = short_name(t)
        name.startsWith(t + "_") ||
        name.endsWith("." + s + "_") ||
        name.startsWith(s + "_")
      }

    val matches: Markup => Boolean = markup =>
      Markup.Entity.Occ.unapply(markup).contains(target_id) ||
        def_site_ref_id(markup).exists(all_ids.contains) ||
        Markup.Entity.unapply(markup).exists {
          case ("bound", name) => name_matches(name)
          case ("fact", name)  => matches_derived(name)
          case _               => false
        }

    snapshot
      .cumulate[List[Text.Range]](
        full_range,
        Nil,
        Rendering.entity_elements,
        _ => {
          case (acc, Text.Info(range, XML.Elem(markup, _))) if matches(markup) =>
            Some(range :: acc)
          case _ => None
        }
      )
      .flatMap(_.info)
      .distinct
  }

  def collect_all_entity_ids(
      target_name: Option[String],
      snapshot: Document.Snapshot
  ): Set[Long] = {
    val short = target_name.map(short_name)
    snapshot
      .cumulate[Set[Long]](
        Text.Range(0, snapshot.node.source.length),
        Set.empty,
        Rendering.entity_elements,
        _ => { case (acc, Text.Info(_, XML.Elem(markup, _))) =>
          val def_id = markup.properties
            .collectFirst { case ("def", v) => v }
            .flatMap(Value.Long.unapply)
          val name_match = Markup.Entity.unapply(markup).exists { case (_, n) =>
            target_name.contains(n) || short.contains(n)
          }
          val no_kind_name_match = !markup.properties.exists(_._1 == "kind") &&
            def_id.isDefined &&
            markup.properties
              .collectFirst { case ("name", v) => v }
              .exists(n => short.contains(n))
          if ((name_match || no_kind_name_match) && def_id.isDefined)
            Some(acc + def_id.get)
          else None
        }
      )
      .flatMap(_.info)
      .toSet
  }

  /* Helpers */

  private def short_name(qualified: String): String = {
    val dot = qualified.lastIndexOf('.')
    if (dot >= 0) qualified.substring(dot + 1) else qualified
  }

  private def def_site_ref_id(markup: Markup): Option[Long] =
    for {
      ref_str <- markup.properties.collectFirst { case ("ref", v) => v }
      ref_id <- Value.Long.unapply(ref_str)
      _ <- markup.properties.collectFirst { case ("def_offset", _) => () }
    } yield ref_id

  /** Walk upward from `start` looking for a session root directory. Prefers directories containing
    * ROOTS; falls back to ROOT.
    */
  def find_session_dir(start: JFile): Option[isabelle.Path] = {
    var roots_dir: Option[JFile] = None
    var root_dir: Option[JFile] = None
    var d = start

    while (d != null) {
      if (roots_dir.isEmpty && new JFile(d, "ROOTS").exists()) roots_dir = Some(d)
      if (root_dir.isEmpty && new JFile(d, "ROOT").exists()) root_dir = Some(d)
      d = d.getParentFile
    }

    roots_dir.orElse(root_dir).map(f => isabelle.Path.explode(f.getPath))
  }

  /* UI helpers */

  private def progress_dialog(
      view: View
  ): (javax.swing.JDialog, javax.swing.JLabel) = {
    val dialog = new javax.swing.JDialog(view, "Renaming…", true)
    val label = new javax.swing.JLabel("Loading theories…")
    val progress_bar = new javax.swing.JProgressBar()
    progress_bar.setIndeterminate(true)
    val panel = new javax.swing.JPanel()
    panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS))
    panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20))
    panel.add(label)
    panel.add(javax.swing.Box.createVerticalStrut(10))
    panel.add(progress_bar)
    dialog.add(panel)
    dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE)
    dialog.pack()
    dialog.setLocationRelativeTo(view)
    (dialog, label)
  }
  private def theory_progress(label: javax.swing.JLabel): isabelle.Progress =
    new isabelle.Progress {
      override def output(msgs: isabelle.Progress.Output): Unit =
        for (msg <- msgs) msg match {
          case thy: isabelle.Progress.Theory =>
            GUI_Thread.later { label.setText(s"Checking ${thy.theory}…") }
          case _ =>
        }
    }
}

object Headless_Handler {

  /* Promise interrupt */

  @volatile private var cancel_promise: Option[Promise[Document.State]] = None

  def cancel(): Unit = {
    cancel_promise.foreach(_.tryFailure(new Exception("Cancelled")))
    cancel_promise = None
  }
  /* Proc state */

  private case class State(
      session: Headless.Session,
      resources: Headless.Resources,
      id: isabelle.UUID.T,
      doc_state: Document.State,
      theory_nodes: List[Document.Node.Name],
      dep_files: List[Document.Node.Name],
      theory_names: List[String],
      master_dir: String,
      session_name: String
  )
  private var state: Option[State] = None

  /* Project resolution */

  private case class ProjectInfo(
      project_session: String,
      parent: String,
      theory_short_names: List[String],
      master_dir: String,
      extra_dirs: List[isabelle.Path]
  )
  private def resolve_project(current_file: String): ProjectInfo = {
    val options = PIDE.options.value
    val dir = new JFile(current_file).getParent
    val extra_dirs = Refactor.find_session_dir(new JFile(dir)).toList
    val sessions =
      JEdit_Session.sessions_structure(dirs = JEdit_Session.session_dirs ::: extra_dirs)
    val project_session = sessions.session_directories
      .get(new JFile(dir).getCanonicalFile)
      .getOrElse(JEdit_Session.logic_name(options))
    val info = sessions(project_session)
    val parent = info.parent.getOrElse(JEdit_Session.logic_name(options))
    val theory_short_names = info.theories.flatMap(_._2.map(_._1))
    val master_dir = info.dir.implode
    ProjectInfo(project_session, parent, theory_short_names, master_dir, extra_dirs)
  }

  /* Proc lifetime mgmt */

  def ensure_running(
      // Start session if one isn't running
      current_file: String,
      progress: isabelle.Progress
  ): Unit = synchronized {
    if (!state.exists(s => is_same_project(s, current_file))) {
      stop()
      val s = start_fresh(current_file, progress)
      state = Some(s)
    } else {
      refresh(progress)
    }
  }
  def refresh(progress: isabelle.Progress): Unit = synchronized {
    // Ensure State object is fresh
    state.foreach { s =>
      s.resources.load_theories(
        s.session,
        s.id,
        s.theory_nodes,
        s.dep_files,
        unicode_symbols = false,
        progress
      )
      val doc_state = await_stable(s.session, s.theory_nodes, progress)
      state = Some(s.copy(doc_state = doc_state))
    }
  }
  def stop(): Unit = synchronized {
    state.foreach { s =>
      s.resources.unload_theories(s.session, s.id, s.theory_nodes)
      s.session.stop()
    }
    state = None
  }

  /* Getters */

  def snapshot(name: Document.Node.Name): Option[Document.Snapshot] =
    state.flatMap { s =>
      s.doc_state.stable_tip_version.map(v => s.doc_state.snapshot(name))
    }
  def nodes: List[Document.Node.Name] =
    state.toList.flatMap(_.theory_nodes)

  /* Internal */
  private def start_fresh(current_file: String, progress: isabelle.Progress): State = {
    // Create a fresh headless sessionn
    val p = resolve_project(current_file)
    val options = PIDE.options.value
    val bg = Sessions.background(
      options,
      session = p.parent,
      dirs = JEdit_Session.session_dirs ::: p.extra_dirs
    )
    val resources = Headless.Resources(options, bg)
    val session = resources.start_session(progress = progress)
    val id = isabelle.UUID.random()

    val import_names = p.theory_short_names.map(thy =>
      resources.import_name(
        Sessions.DRAFT,
        session.master_directory(p.master_dir),
        thy
      ) -> isabelle.Position.none
    )
    val deps = resources.dependencies(import_names, progress = progress).check_errors
    val theory_nodes = deps.theories
    val dep_files = deps.loaded_files

    resources.load_theories(session, id, theory_nodes, dep_files, unicode_symbols = false, progress)
    val doc_state = await_stable(session, theory_nodes, progress)

    State(
      session,
      resources,
      id,
      doc_state,
      theory_nodes,
      dep_files,
      p.theory_short_names,
      p.master_dir,
      p.project_session
    )
  }
  private def is_same_project(s: State, file: String): Boolean = {
    // check if file belongs to the same session/ROOT
    resolve_project(file).project_session == s.session_name
  }
  private def await_stable(
      // Wait for all theory nodes to be consolidated
      session: Headless.Session,
      theory_nodes: List[Document.Node.Name],
      progress: isabelle.Progress
  ): Document.State = {
    val done = Promise[Document.State]()
    cancel_promise = Some(done)
    val reported = scala.collection.mutable.Set.empty[Document.Node.Name]

    val consumer = isabelle.Session.Consumer[isabelle.Session.Commands_Changed]("await_stable") {
      _ =>
        if (progress.stopped) {
          done.tryFailure(new Exception("Cancelled"))
          ()
        } else {
          val state = session.get_state()
          for (version <- state.stable_tip_version) {
            for (name <- theory_nodes) {
              if (!reported.contains(name) && state.node_consolidated(version, name)) {
                reported += name
                val display_name = name.theory.stripPrefix("Draft.")
                progress.theory(isabelle.Progress.Theory(display_name, percentage = Some(100)))
              }
            }
            if (theory_nodes.forall(name => state.node_consolidated(version, name))) {
              done.trySuccess(state)
              ()
            }
          }
        }
    }
    session.commands_changed += consumer
    val state = session.get_state()
    for (version <- state.stable_tip_version) {
      if (theory_nodes.forall(name => state.node_consolidated(version, name))) {
        done.trySuccess(state)
      }
    }

    try { Await.result(done.future, Duration.Inf) }
    finally {
      session.commands_changed -= consumer
      cancel_promise = None
    }

  }
}
