package isabelle.jedit

import isabelle.{GUI_Thread, Markup, Text, Document}
import javax.swing.JOptionPane
import org.gjt.sp.jedit.View
import org.gjt.sp.jedit.jEdit

import scala.concurrent.{Promise, Await}
import scala.concurrent.duration.Duration

object Rename {

  case class RenameResult(
      targetId: Option[Long],
      occurrences: List[(Document.Node.Name, List[Text.Range])]
  )

  // Known suffixes generated by Isabelle for derived constants
  // ## These are not currently being used ##
  private val derived_suffixes: List[String] =
    List("_def", "_simps", "_cases")

  /* Entry point */

  def apply(view: View): Unit = {
    GUI_Thread.now {
      val text_area = view.getTextArea()

      val entities =
        (for {
          doc_view <- Document_View.get(text_area)
          snapshot = Document_View.rendering(doc_view).snapshot
        } yield JEditUtils.entity_at_caret(text_area, snapshot)).getOrElse(Nil)

      val target_name_opt = entities.collectFirst { case ("constant", name, _) => name }

      target_name_opt match {
        case None =>
          JOptionPane.showMessageDialog(
            view,
            "No constant found at caret.",
            "Rename",
            JOptionPane.INFORMATION_MESSAGE
          )
        case Some(target_name) =>
          run_rename(view, target_name)
      }
    }
  }

  private def run_rename(view: View, target_name: String): Unit = {
    val current_file = view.getBuffer.getPath

    val (dialog, label) = JEditUtils.progress_dialog(view)

    jEdit.getBuffers.foreach { buf =>
      if (buf.isDirty) buf.save(view, null)
    }

    val result_promise = Promise[RenameResult]()
    val progress = JEditUtils.theory_progress(label)

    dialog.addWindowListener(new java.awt.event.WindowAdapter {
      override def windowClosing(e: java.awt.event.WindowEvent): Unit = {
        progress.stop()
        Headless_Handler.cancel()
        label.setText("Cancelling…")
      }
    })

    val thread_name = s"isabelle-rename-$target_name"
    new Thread(
      () => {
        try {
          val result = find_all_occurrences(target_name, current_file, progress)
          result_promise.success(result)
          ()
        } catch {
          case e: Throwable =>
            result_promise.failure(e)
            ()
        } finally {
          GUI_Thread.later { dialog.dispose() }
        }
      },
      thread_name
    ).start()

    dialog.setVisible(true) // blocks until dialog is gone

    if (!progress.stopped) {
      try {
        val rename_result = Await.result(result_promise.future, Duration.Inf)
        prompt_and_apply(view, rename_result)
      } catch {
        case e: Throwable =>
          JOptionPane.showMessageDialog(
            view,
            e.getMessage,
            "Rename error",
            JOptionPane.ERROR_MESSAGE
          )
      }
    }
  }

  /* All occurrences across all theories in ROOT */

  private def find_all_occurrences(
      target_name: String,
      current_file: String,
      progress: isabelle.Progress
  ): RenameResult = {

    Headless_Handler.ensure_running(current_file, progress)
    val defining_theory = target_name.take(target_name.lastIndexOf('.'))
    val defining_node = Headless_Handler.nodes.find { name =>
      val short = name.theory.drop(name.theory.lastIndexOf('.') + 1)
      short == defining_theory
    }

    val (headless_id, all_ids) = defining_node match {
      case None => (None, Set.empty[Long])
      case Some(name) =>
        val snapshot = Headless_Handler.snapshot(name).get
        // NOTE: entity_by_name and collect_all_entity_ids still take Option[String]
         // (I should un-optional them)
        val id = MarkupUtils.entity_by_name("constant", Some(target_name), snapshot)
        val ids = MarkupUtils.collect_all_entity_ids(Some(target_name), snapshot)
        (id, ids ++ id.toSet)
    }

    val occurrences = for {
      id <- headless_id.toList
      name <- Headless_Handler.nodes
      snapshot <- Headless_Handler.snapshot(name).toList
      ranges = find_occurrences(id, all_ids, target_name, snapshot)
      if ranges.nonEmpty
    } yield (name, ranges)
    RenameResult(headless_id, occurrences)

  }

  /* UI: prompt user for new name and apply */

  private def prompt_and_apply(
      view: View,
      result: RenameResult
  ): Unit = {
    val ranges_str =
      if (result.occurrences.isEmpty) "  (none)"
      else
        result.occurrences
          .map { case (node_name, ranges) =>
            val header = s"  ${node_name.theory}:"
            val lines = ranges.map(r => s"    [${r.start}, ${r.stop})").mkString("\n")
            s"$header\n$lines"
          }
          .mkString("\n")

    val new_name: Option[String] = Option(
      JOptionPane.showInputDialog(
        view,
        s"ID: ${result.targetId.getOrElse("none")}\nMatches:\n$ranges_str\n\nEnter replacement name:"
      )
    )
    new_name match {
      case Some(name) if name.nonEmpty =>
        val edits = build_rename_edits(result.occurrences, name)
        Edit.apply_to_files(edits)
        reload_buffers(view, result.occurrences.map(_._1))
      case _ => // User cancelled or left blank
    }

  }

  /* File rewriting */

  private def build_rename_edits(
      occurrences: List[(Document.Node.Name, List[Text.Range])],
      new_name: String
  ): List[(Document.Node.Name, Edit)] =
    for {
      (node, ranges) <- occurrences
      r <- ranges
    } yield node -> Edit.Replace(r, new_name)

  private def reload_buffers(view: View, nodes: List[Document.Node.Name]): Unit =
    nodes.foreach { node_name =>
      val buf = jEdit.getBuffer(node_name.node)
      if (buf != null) buf.reload(view)
    }

  /* Entity occurrence finding */

  def find_occurrences(
      target_id: Long,
      all_ids: Set[Long],
      target_name: String,
      snapshot: Document.Snapshot
  ): List[Text.Range] = {
    val name_matches: String => Boolean = name =>
      target_name == name || target_name.endsWith("." + name)

    // Matches derived names (e.g. myConst_def, myConst_simps)
    // Not an ideal solution, but derived names doesn't match
    // user-defined suffixes
    val short = MarkupUtils.short_name(target_name)
    val matches_derived: String => Boolean = name =>
      name.startsWith(target_name + "_") ||
        name.endsWith("." + short + "_") ||
        name.startsWith(short + "_")

    MarkupUtils.collect_ranges(
      snapshot,
      markup =>
        Markup.Entity.Occ.unapply(markup).contains(target_id) ||
          MarkupUtils.ref_to_def_id(markup).exists(all_ids.contains) ||
          Markup.Entity.unapply(markup).exists {
            case ("bound", name) => name_matches(name)
            case ("fact", name)  => matches_derived(name)
            case _               => false
          }
    )

  }

}
