package isabelle.jedit

import isabelle.{GUI_Thread, Markup, Text, Document}
import javax.swing.JOptionPane
import org.gjt.sp.jedit.View
import org.gjt.sp.jedit.jEdit

import scala.concurrent.{Promise, Await}
import scala.concurrent.duration.Duration

object Rename {

  case class RenameResult(
      targetId: Option[Long],
      occurrences: List[(Document.Node.Name, List[Text.Range])]
  )

  // Known suffixes generated by Isabelle for derived constants
  // ## These are not currently being used ##
  private val derived_suffixes: List[String] =
    List("_def", "_simps", "_cases")

  /* Entry point */

  def apply(view: View): Unit = {
    GUI_Thread.now {
      val text_area = view.getTextArea()

      val entities =
        (for {
          doc_view <- Document_View.get(text_area)
          snapshot = Document_View.rendering(doc_view).snapshot
        } yield JEditUtils.entity_at_caret(text_area, snapshot)).getOrElse(Nil)

      val target_name = entities.collectFirst { case ("constant", name, _) => name }
      val old_short_name = target_name.map(MarkupUtils.short_name)
      val current_file = view.getBuffer.getPath

      val (dialog, label) = JEditUtils.progress_dialog(view)

      jEdit.getBuffers.foreach { buf =>
        if (buf.isDirty) buf.save(view, null)
      }

      val result_promise = Promise[RenameResult]()
      val progress = JEditUtils.theory_progress(label)

      dialog.addWindowListener(new java.awt.event.WindowAdapter {
        override def windowClosing(e: java.awt.event.WindowEvent): Unit = {
          progress.stop()
          Headless_Handler.cancel()
          label.setText("Cancelling…")
        }
      })

      val thread_name = s"isabelle-rename-${target_name.getOrElse("unknown")}"
      new Thread(
        () => {
          try {
            val result = find_all_occurrences(target_name, current_file, progress)
            result_promise.success(result)
            ()
          } catch {
            case e: Throwable =>
              result_promise.failure(e)
              ()
          } finally {
            GUI_Thread.later { dialog.dispose() }
          }
        },
        thread_name
      ).start()

      dialog.setVisible(true) // blocks until dialog is gone

      if (!progress.stopped) {
        try {
          val rename_result = Await.result(result_promise.future, Duration.Inf)
          prompt_and_apply(view, rename_result, old_short_name)
        } catch {
          case e: Throwable =>
            JOptionPane.showMessageDialog(
              view,
              e.getMessage,
              "Rename error",
              JOptionPane.ERROR_MESSAGE
            )
        }
      }
    }
  }

  /* All occurrences across all theories in ROOT */

  private def find_all_occurrences(
      target_name: Option[String],
      current_file: String,
      progress: isabelle.Progress
  ): RenameResult = {

    Headless_Handler.ensure_running(current_file, progress)
    val defining_theory = target_name.map(n => n.take(n.lastIndexOf('.')))
    val defining_node = Headless_Handler.nodes.find { name =>
      val short = name.theory.drop(name.theory.lastIndexOf('.') + 1)
      defining_theory.contains(short)
    }

    val (headless_id, all_ids) = defining_node match {
      case None => (None, Set.empty[Long])
      case Some(name) =>
        val snapshot = Headless_Handler.snapshot(name).get
        val id = MarkupUtils.entity_by_name("constant", target_name, snapshot)
        val ids = MarkupUtils.collect_all_entity_ids(target_name, snapshot)
        (id, ids ++ id.toSet)
    }

    val occurrences = for {
      id <- headless_id.toList
      name <- Headless_Handler.nodes
      snapshot <- Headless_Handler.snapshot(name).toList
      ranges = find_occurrences(id, all_ids, target_name, snapshot)
      if ranges.nonEmpty
    } yield (name, ranges)
    RenameResult(headless_id, occurrences)

  }

  /* UI: prompt user for new name and apply */

  private def prompt_and_apply(
      view: View,
      result: RenameResult,
      old_short_name: Option[String]
  ): Unit = {
    val ranges_str =
      if (result.occurrences.isEmpty) "  (none)"
      else
        result.occurrences
          .map { case (node_name, ranges) =>
            val header = s"  ${node_name.theory}:"
            val lines = ranges.map(r => s"    [${r.start}, ${r.stop})").mkString("\n")
            s"$header\n$lines"
          }
          .mkString("\n")

    val new_name: Option[String] = Option(
      JOptionPane.showInputDialog(
        view,
        s"ID: ${result.targetId.getOrElse("none")}\nMatches:\n$ranges_str\n\nEnter replacement name:"
      )
    )

    (new_name, old_short_name) match {
      case (Some(name), Some(old_name)) if name.nonEmpty =>
        apply_renames(result.occurrences, old_name, name)
        reload_buffers(view, result.occurrences.map(_._1))
      case _ => // User cancelled or left blank
    }
  }

  /* File rewriting */

  private def apply_renames(
      occurrences: List[(Document.Node.Name, List[Text.Range])],
      old_name: String,
      new_name: String
  ): Unit =
    occurrences.foreach { case (node_name, ranges) =>
      val path = isabelle.Path.explode(node_name.node)
      val text = isabelle.File.read(path)
      val result = ranges.sortBy(_.start).reverse.foldLeft(text) { (t, r) =>
        t.substring(0, r.start) + t.substring(r.start, r.stop).replace(old_name, new_name) +
          t.substring(r.stop)
      }
      isabelle.File.write(path, result)
    }
  private def reload_buffers(view: View, nodes: List[Document.Node.Name]): Unit =
    nodes.foreach { node_name =>
      val buf = jEdit.getBuffer(node_name.node)
      if (buf != null) buf.reload(view)
    }
  /* Entity occurrence finding */

  def find_occurrences(
      target_id: Long,
      all_ids: Set[Long],
      target_name: Option[String],
      snapshot: Document.Snapshot
  ): List[Text.Range] = {
    val name_matches: String => Boolean = name =>
      target_name.exists(t => t == name || t.endsWith("." + name))

    // Matches derived names (e.g. myConst_def, myConst_simps)
    // Not an ideal solution, but derived names doesn't match
    // user-defined suffixes
    val matches_derived: String => Boolean = name =>
      target_name.exists { t =>
        val s = MarkupUtils.short_name(t)
        name.startsWith(t + "_") ||
        name.endsWith("." + s + "_") ||
        name.startsWith(s + "_")
      }

    MarkupUtils.collect_ranges(
      snapshot,
      markup =>
        Markup.Entity.Occ.unapply(markup).contains(target_id) ||
          MarkupUtils.ref_to_def_id(markup).exists(all_ids.contains) ||
          Markup.Entity.unapply(markup).exists {
            case ("bound", name) => name_matches(name)
            case ("fact", name)  => matches_derived(name)
            case _               => false
          }
    )

  }



}
